server:
  port: 8091
spring:
  application:
    name: Project-Budget-Planner
  profiles:
    active: prod # dev for dev environment (application-dev.yml), and prod for production
  jpa:
    open-in-view: false
